name: fastai-203
channels:
  - pytorch
  - fastai
  - defaults
  - conda-forge
dependencies:
  - fastai=1.0.60
  - jupyter=1.0.0
  - jupyterlab=2.0.1
  - matplotlib=3.1.3
  - nbdime=2.0.0
  - numpy=1.18.1
  - pandas=1.0.2
  - scikit-learn=0.22.1
  - seaborn=0.10.0
  - spacy=2.1.8
  - transformers=2.1.1
  - pip:
    - fastscript==0.1.4
    - nbdev==0.2.15
